leftnav:
- identifier: 306a747d-aa69-d374-4485-594e7e94ebef
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 3d0d08a5-a82d-3c0d-2f8a-020cbc2638ec
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: c2e6b8ad-ac69-08c4-2f08-1ca4c783ef48
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: c5cfbfca-c593-0461-0d26-864fd8574ef1
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 73312e29-6ad9-c115-9af8-7d7fa5ac4489
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 50
